version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - sales-service
      - delivery-service
    networks:
      - app-network

  # Sales Service
  sales-service:
    build: ./sales-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=sales-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sales_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - sales-db
      - rabbitmq
      - redis
    networks:
      - app-network

  # Delivery Service
  delivery-service:
    build: ./delivery-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DB_HOST=delivery-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=delivery_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - delivery-db
      - rabbitmq
      - redis
    networks:
      - app-network

  # Sales Database
  sales-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_db
    volumes:
      - sales-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Delivery Database
  delivery-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery_db
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # PGAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - sales-db
      - delivery-db
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  sales-db-data:
  delivery-db-data:
